main: "com.soyaldo.actionapi.ActionAPI"

name: "action-api"
description: "Action API for your minecraft plugins."
version: "1.7.0"
author: "SoyAldo"
website: "https://soyaldo.com/project/action-api"

api-version: 1.13
softdepend: [ "PlaceholderAPI", "Vault" ]