main: "com.soyaldo.actionapi.ActionAPI"

name: "action-api"
version: "1.6.0"
description: "Action API for your minecraft plugins."
website: "https://soyaldo.com/project/action-api"

api-version: 1.13
author: SoyAldo
softdepend: [ PlaceholderAPI, Vault ]