name: action-api-testing
version: '${project.version}'
main: com.soyaldo.actionapitesting.ActionApiTesting
api-version: 1.16
authors: [ Soyaldo ]
description: action-api testing plugin.
softdepend: [ PlaceholderAPI ]
commands:
  ActionApiTesting:
    description: "With this command you can test actions and reload this plugin."